/* Generated by Yosys 0.58+80 (git sha1 37875fded, clang++ 18.1.8 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "Param_paritysel_mux.v:2.1-20.10" *)
module Param_paritysel_mux(sel, data_a, data_b, data_out);
  (* src = "Param_paritysel_mux.v:7.18-7.21" *)
  input [4:0] sel;
  wire [4:0] sel;
  (* src = "Param_paritysel_mux.v:8.24-8.30" *)
  input [7:0] data_a;
  wire [7:0] data_a;
  (* src = "Param_paritysel_mux.v:9.24-9.30" *)
  input [7:0] data_b;
  wire [7:0] data_b;
  (* src = "Param_paritysel_mux.v:11.25-11.33" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  assign data_out[0] = sel[0] ? data_b[0] : data_a[0];
  assign data_out[1] = sel[0] ? data_b[1] : data_a[1];
  assign data_out[2] = sel[0] ? data_b[2] : data_a[2];
  assign data_out[3] = sel[0] ? data_b[3] : data_a[3];
  assign data_out[4] = sel[0] ? data_b[4] : data_a[4];
  assign data_out[5] = sel[0] ? data_b[5] : data_a[5];
  assign data_out[6] = sel[0] ? data_b[6] : data_a[6];
  assign data_out[7] = sel[0] ? data_b[7] : data_a[7];
endmodule
